"""Fix pincode

Revision ID: fb1699959aa1
Revises: 36cf19f7f577
Create Date: 2025-07-14 18:29:41.882617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1699959aa1'
down_revision = '36cf19f7f577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lots', schema=None) as batch_op:
        batch_op.alter_column('pincode',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=6),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lots', schema=None) as batch_op:
        batch_op.alter_column('pincode',
               existing_type=sa.String(length=6),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
